# 03 — Modelos Baseline y Evaluación
**CRISP-DM: Modelado + Evaluación** · Etapa 1: *Baseline (≥3 algoritmos) + tabla comparativa + interpretabilidad*

Requiere `pip install -r requirements.txt` (scikit-learn, xgboost, shap).
Usa `data/processed/dataset_modelado.csv` generado en el notebook 02.

In [1]:
import sys
from pathlib import Path
sys.path.append(str(Path.cwd().parent / "src"))
import pandas as pd
from prediccion_precios import features as ft, evaluation as ev, config
from prediccion_precios import models_baseline as mb, interpretability as it
pd.set_option("display.width",160); pd.set_option("display.max_columns",60)

In [2]:
data = pd.read_csv(config.DATASET_MODELADO, parse_dates=[config.COL_FECHA])
n_antes = len(data)
# dropna=True: descarta el NaN estructural de lags/medias móviles en las
# primeras semanas de cada producto (documentado y tratado en el notebook 02)
X, y = ft.construir_matriz_modelado(data)
X = X.astype(float)
n_descartadas = n_antes - len(X)
print(f"Filas descartadas por NaN estructural (lags/medias móviles iniciales): "
      f"{n_descartadas} ({n_descartadas / n_antes * 100:.2f}%)")
X_train, X_test, y_train, y_test = ev.split_temporal(X, y)
print("X", X.shape, "| train", len(X_train), "| test", len(X_test))

Filas descartadas por NaN estructural (lags/medias móviles iniciales): 40 (4.85%)
X (785, 34) | train 628 | test 157

## 1. Entrenar los 3 baselines (Regresión Lineal, Random Forest, XGBoost)

In [3]:
modelos = mb.entrenar_todos(X_train, y_train)
list(modelos.keys())

['regresion_lineal', 'random_forest', 'xgboost']

## 2. Tabla comparativa de métricas (MAE / RMSE / MAPE / R²)

In [4]:
resultados = {n: ev.calcular_metricas(y_test, m.predict(X_test)) for n, m in modelos.items()}
tabla = ev.tabla_comparativa(resultados)
print("Meta objetivo: MAPE <", config.META_MAPE_OBJETIVO*100, "%")
tabla

Meta objetivo: MAPE < 15.0 %

                     MAE    RMSE  MAPE_%      R2
Modelo
regresion_lineal  1.4209  2.2990  5.7303  0.9941
random_forest     1.7593  2.7454  6.2069  0.9916
xgboost           1.6975  2.5806  7.1450  0.9926

## 3. Validación cruzada temporal (ventana expansiva)
Se pasa la *fábrica* del modelo (`mb.FABRICAS[nombre]`) para re-crearlo en cada fold.

In [5]:
for nombre, fabrica in mb.FABRICAS.items():
    cv = ev.validacion_cruzada_temporal(fabrica, X, y, n_splits=config.CV_SPLITS)
    print(nombre, "-> MAPE %:", cv["MAPE_%"], "| R2:", cv["R2"])

regresion_lineal -> MAPE %: {'media': 18.8262, 'std': 23.3825} | R2: {'media': 0.4536, 'std': 1.0756}

random_forest -> MAPE %: {'media': 8.2271, 'std': 3.6959} | R2: {'media': 0.955, 'std': 0.0567}

xgboost -> MAPE %: {'media': 9.4933, 'std': 4.1656} | R2: {'media': 0.9196, 'std': 0.1096}

## 4. Interpretabilidad — importancia de variables + SHAP

In [6]:
mejor = modelos["xgboost"]
display(it.importancia_variables(mejor, X.columns).head(15))
it.graficar_importancia(mejor, X.columns)            # -> reports/figures/importancia_variables.png
it.explicar_shap(mejor, X_test)                       # -> reports/figures/shap_summary.png

              feature  importancia
0       media_movil_4     0.368482
1         precio_lag1     0.164747
2      media_movil_12     0.143490
3         precio_lag4     0.115933
4   rendimiento_kg_ha     0.077863
5         precio_lag8     0.061020
6         precio_lag2     0.047418
7       media_movil_8     0.008902
8             area_ha     0.003247
9        produccion_t     0.002617
10      grupo_NARANJA     0.000983
11               Anio     0.000944
12     ipc_transporte     0.000788
13        semana_anio     0.000505
14             diesel     0.000483

PermutationExplainer explainer:   1%|          | 1/157 [00:00<?, ?it/s]

PermutationExplainer explainer:   2%|▏         | 3/157 [00:26<00:30,  4.98it/s]

PermutationExplainer explainer:   3%|▎         | 4/157 [00:26<00:44,  3.48it/s]

PermutationExplainer explainer:   3%|▎         | 5/157 [00:27<00:52,  2.87it/s]

PermutationExplainer explainer:   4%|▍         | 6/157 [00:27<01:04,  2.35it/s]

PermutationExplainer explainer:   4%|▍         | 7/157 [00:28<01:02,  2.40it/s]

PermutationExplainer explainer:   5%|▌         | 8/157 [00:28<01:03,  2.34it/s]

PermutationExplainer explainer:   6%|▌         | 9/157 [00:29<01:02,  2.37it/s]

PermutationExplainer explainer:   6%|▋         | 10/157 [00:29<01:04,  2.28it/s]

PermutationExplainer explainer:   7%|▋         | 11/157 [00:30<01:09,  2.09it/s]

PermutationExplainer explainer:   8%|▊         | 12/157 [00:30<01:04,  2.25it/s]

PermutationExplainer explainer:   8%|▊         | 13/157 [00:30<01:03,  2.28it/s]

PermutationExplainer explainer:   9%|▉         | 14/157 [00:31<01:13,  1.94it/s]

PermutationExplainer explainer:  10%|▉         | 15/157 [00:31<01:03,  2.25it/s]

PermutationExplainer explainer:  10%|█         | 16/157 [00:32<00:56,  2.50it/s]

PermutationExplainer explainer:  11%|█         | 17/157 [00:32<00:52,  2.66it/s]

PermutationExplainer explainer:  11%|█▏        | 18/157 [00:32<00:48,  2.86it/s]

PermutationExplainer explainer:  12%|█▏        | 19/157 [00:33<00:46,  3.00it/s]

PermutationExplainer explainer:  13%|█▎        | 20/157 [00:33<00:42,  3.23it/s]

PermutationExplainer explainer:  13%|█▎        | 21/157 [00:33<00:49,  2.73it/s]

PermutationExplainer explainer:  14%|█▍        | 22/157 [00:34<00:49,  2.70it/s]

PermutationExplainer explainer:  15%|█▍        | 23/157 [00:34<00:45,  2.93it/s]

PermutationExplainer explainer:  15%|█▌        | 24/157 [00:34<00:44,  3.01it/s]

PermutationExplainer explainer:  16%|█▌        | 25/157 [00:35<00:42,  3.07it/s]

PermutationExplainer explainer:  17%|█▋        | 26/157 [00:35<00:43,  3.01it/s]

PermutationExplainer explainer:  17%|█▋        | 27/157 [00:35<00:42,  3.06it/s]

PermutationExplainer explainer:  18%|█▊        | 28/157 [00:36<00:39,  3.25it/s]

PermutationExplainer explainer:  18%|█▊        | 29/157 [00:36<00:37,  3.46it/s]

PermutationExplainer explainer:  19%|█▉        | 30/157 [00:36<00:37,  3.41it/s]

PermutationExplainer explainer:  20%|█▉        | 31/157 [00:36<00:35,  3.57it/s]

PermutationExplainer explainer:  20%|██        | 32/157 [00:37<00:34,  3.59it/s]

PermutationExplainer explainer:  21%|██        | 33/157 [00:37<00:34,  3.54it/s]

PermutationExplainer explainer:  22%|██▏       | 34/157 [00:37<00:35,  3.48it/s]

PermutationExplainer explainer:  22%|██▏       | 35/157 [00:38<00:33,  3.68it/s]

PermutationExplainer explainer:  23%|██▎       | 36/157 [00:38<00:31,  3.84it/s]

PermutationExplainer explainer:  24%|██▎       | 37/157 [00:38<00:30,  3.95it/s]

PermutationExplainer explainer:  24%|██▍       | 38/157 [00:38<00:29,  4.01it/s]

PermutationExplainer explainer:  25%|██▍       | 39/157 [00:39<00:31,  3.79it/s]

PermutationExplainer explainer:  25%|██▌       | 40/157 [00:39<00:29,  3.95it/s]

PermutationExplainer explainer:  26%|██▌       | 41/157 [00:39<00:28,  4.02it/s]

PermutationExplainer explainer:  27%|██▋       | 42/157 [00:39<00:28,  4.05it/s]

PermutationExplainer explainer:  27%|██▋       | 43/157 [00:39<00:29,  3.92it/s]

PermutationExplainer explainer:  28%|██▊       | 44/157 [00:40<00:29,  3.82it/s]

PermutationExplainer explainer:  29%|██▊       | 45/157 [00:40<00:28,  3.92it/s]

PermutationExplainer explainer:  29%|██▉       | 46/157 [00:40<00:29,  3.76it/s]

PermutationExplainer explainer:  30%|██▉       | 47/157 [00:41<00:29,  3.70it/s]

PermutationExplainer explainer:  31%|███       | 48/157 [00:41<00:31,  3.50it/s]

PermutationExplainer explainer:  31%|███       | 49/157 [00:41<00:29,  3.65it/s]

PermutationExplainer explainer:  32%|███▏      | 50/157 [00:41<00:28,  3.78it/s]

PermutationExplainer explainer:  32%|███▏      | 51/157 [00:42<00:27,  3.79it/s]

PermutationExplainer explainer:  33%|███▎      | 52/157 [00:42<00:29,  3.56it/s]

PermutationExplainer explainer:  34%|███▍      | 53/157 [00:42<00:27,  3.72it/s]

PermutationExplainer explainer:  34%|███▍      | 54/157 [00:42<00:26,  3.86it/s]

PermutationExplainer explainer:  35%|███▌      | 55/157 [00:43<00:25,  3.93it/s]

PermutationExplainer explainer:  36%|███▌      | 56/157 [00:43<00:25,  4.03it/s]

PermutationExplainer explainer:  36%|███▋      | 57/157 [00:43<00:25,  3.88it/s]

PermutationExplainer explainer:  37%|███▋      | 58/157 [00:43<00:25,  3.95it/s]

PermutationExplainer explainer:  38%|███▊      | 59/157 [00:44<00:24,  4.02it/s]

PermutationExplainer explainer:  38%|███▊      | 60/157 [00:44<00:23,  4.07it/s]

PermutationExplainer explainer:  39%|███▉      | 61/157 [00:44<00:23,  4.09it/s]

PermutationExplainer explainer:  39%|███▉      | 62/157 [00:44<00:24,  3.95it/s]

PermutationExplainer explainer:  40%|████      | 63/157 [00:45<00:24,  3.85it/s]

PermutationExplainer explainer:  41%|████      | 64/157 [00:45<00:23,  4.01it/s]

PermutationExplainer explainer:  41%|████▏     | 65/157 [00:45<00:22,  4.08it/s]

PermutationExplainer explainer:  42%|████▏     | 66/157 [00:45<00:22,  4.01it/s]

PermutationExplainer explainer:  43%|████▎     | 67/157 [00:46<00:22,  3.99it/s]

PermutationExplainer explainer:  43%|████▎     | 68/157 [00:46<00:22,  4.02it/s]

PermutationExplainer explainer:  44%|████▍     | 69/157 [00:46<00:21,  4.09it/s]

PermutationExplainer explainer:  45%|████▍     | 70/157 [00:46<00:20,  4.18it/s]

PermutationExplainer explainer:  45%|████▌     | 71/157 [00:47<00:21,  4.05it/s]

PermutationExplainer explainer:  46%|████▌     | 72/157 [00:47<00:21,  3.96it/s]

PermutationExplainer explainer:  46%|████▋     | 73/157 [00:47<00:21,  3.98it/s]

PermutationExplainer explainer:  47%|████▋     | 74/157 [00:47<00:20,  4.07it/s]

PermutationExplainer explainer:  48%|████▊     | 75/157 [00:48<00:19,  4.15it/s]

PermutationExplainer explainer:  48%|████▊     | 76/157 [00:48<00:20,  3.98it/s]

PermutationExplainer explainer:  49%|████▉     | 77/157 [00:48<00:19,  4.05it/s]

PermutationExplainer explainer:  50%|████▉     | 78/157 [00:48<00:19,  4.14it/s]

PermutationExplainer explainer:  50%|█████     | 79/157 [00:49<00:18,  4.12it/s]

PermutationExplainer explainer:  51%|█████     | 80/157 [00:49<00:19,  4.01it/s]

PermutationExplainer explainer:  52%|█████▏    | 81/157 [00:49<00:20,  3.73it/s]

PermutationExplainer explainer:  52%|█████▏    | 82/157 [00:49<00:19,  3.85it/s]

PermutationExplainer explainer:  53%|█████▎    | 83/157 [00:50<00:18,  3.95it/s]

PermutationExplainer explainer:  54%|█████▎    | 84/157 [00:50<00:17,  4.08it/s]

PermutationExplainer explainer:  54%|█████▍    | 85/157 [00:50<00:17,  4.10it/s]

PermutationExplainer explainer:  55%|█████▍    | 86/157 [00:50<00:18,  3.94it/s]

PermutationExplainer explainer:  55%|█████▌    | 87/157 [00:51<00:17,  4.01it/s]

PermutationExplainer explainer:  56%|█████▌    | 88/157 [00:51<00:16,  4.11it/s]

PermutationExplainer explainer:  57%|█████▋    | 89/157 [00:51<00:16,  4.15it/s]

PermutationExplainer explainer:  57%|█████▋    | 90/157 [00:51<00:16,  4.00it/s]

PermutationExplainer explainer:  58%|█████▊    | 91/157 [00:52<00:17,  3.87it/s]

PermutationExplainer explainer:  59%|█████▊    | 92/157 [00:52<00:16,  3.86it/s]

PermutationExplainer explainer:  59%|█████▉    | 93/157 [00:52<00:16,  3.92it/s]

PermutationExplainer explainer:  60%|█████▉    | 94/157 [00:52<00:15,  4.00it/s]

PermutationExplainer explainer:  61%|██████    | 95/157 [00:53<00:16,  3.84it/s]

PermutationExplainer explainer:  61%|██████    | 96/157 [00:53<00:15,  3.88it/s]

PermutationExplainer explainer:  62%|██████▏   | 97/157 [00:53<00:15,  3.92it/s]

PermutationExplainer explainer:  62%|██████▏   | 98/157 [00:53<00:14,  3.97it/s]

PermutationExplainer explainer:  63%|██████▎   | 99/157 [00:54<00:14,  4.09it/s]

PermutationExplainer explainer:  64%|██████▎   | 100/157 [00:54<00:14,  3.98it/s]

PermutationExplainer explainer:  64%|██████▍   | 101/157 [00:54<00:13,  4.07it/s]

PermutationExplainer explainer:  65%|██████▍   | 102/157 [00:54<00:13,  4.10it/s]

PermutationExplainer explainer:  66%|██████▌   | 103/157 [00:55<00:12,  4.18it/s]

PermutationExplainer explainer:  66%|██████▌   | 104/157 [00:55<00:12,  4.23it/s]

PermutationExplainer explainer:  67%|██████▋   | 105/157 [00:55<00:13,  3.98it/s]

PermutationExplainer explainer:  68%|██████▊   | 106/157 [00:55<00:12,  4.09it/s]

PermutationExplainer explainer:  68%|██████▊   | 107/157 [00:56<00:12,  4.15it/s]

PermutationExplainer explainer:  69%|██████▉   | 108/157 [00:56<00:11,  4.18it/s]

PermutationExplainer explainer:  69%|██████▉   | 109/157 [00:56<00:11,  4.22it/s]

PermutationExplainer explainer:  70%|███████   | 110/157 [00:56<00:11,  4.01it/s]

PermutationExplainer explainer:  71%|███████   | 111/157 [00:57<00:11,  4.08it/s]

PermutationExplainer explainer:  71%|███████▏  | 112/157 [00:57<00:11,  4.07it/s]

PermutationExplainer explainer:  72%|███████▏  | 113/157 [00:57<00:10,  4.04it/s]

PermutationExplainer explainer:  73%|███████▎  | 114/157 [00:57<00:11,  3.88it/s]

PermutationExplainer explainer:  73%|███████▎  | 115/157 [00:58<00:10,  3.86it/s]

PermutationExplainer explainer:  74%|███████▍  | 116/157 [00:58<00:10,  3.96it/s]

PermutationExplainer explainer:  75%|███████▍  | 117/157 [00:58<00:10,  3.98it/s]

PermutationExplainer explainer:  75%|███████▌  | 118/157 [00:58<00:10,  3.87it/s]

PermutationExplainer explainer:  76%|███████▌  | 119/157 [00:59<00:10,  3.56it/s]

PermutationExplainer explainer:  76%|███████▋  | 120/157 [00:59<00:09,  3.70it/s]

PermutationExplainer explainer:  77%|███████▋  | 121/157 [00:59<00:09,  3.85it/s]

PermutationExplainer explainer:  78%|███████▊  | 122/157 [00:59<00:08,  3.96it/s]

PermutationExplainer explainer:  78%|███████▊  | 123/157 [01:00<00:08,  3.86it/s]

PermutationExplainer explainer:  79%|███████▉  | 124/157 [01:00<00:08,  3.77it/s]

PermutationExplainer explainer:  80%|███████▉  | 125/157 [01:00<00:08,  3.90it/s]

PermutationExplainer explainer:  80%|████████  | 126/157 [01:00<00:07,  3.99it/s]

PermutationExplainer explainer:  81%|████████  | 127/157 [01:01<00:07,  4.05it/s]

PermutationExplainer explainer:  82%|████████▏ | 128/157 [01:01<00:07,  4.10it/s]

PermutationExplainer explainer:  82%|████████▏ | 129/157 [01:01<00:07,  3.97it/s]

PermutationExplainer explainer:  83%|████████▎ | 130/157 [01:01<00:06,  3.95it/s]

PermutationExplainer explainer:  83%|████████▎ | 131/157 [01:02<00:06,  3.80it/s]

PermutationExplainer explainer:  84%|████████▍ | 132/157 [01:02<00:06,  3.83it/s]

PermutationExplainer explainer:  85%|████████▍ | 133/157 [01:02<00:06,  3.82it/s]

PermutationExplainer explainer:  85%|████████▌ | 134/157 [01:03<00:06,  3.79it/s]

PermutationExplainer explainer:  86%|████████▌ | 135/157 [01:03<00:05,  3.88it/s]

PermutationExplainer explainer:  87%|████████▋ | 136/157 [01:03<00:05,  3.86it/s]

PermutationExplainer explainer:  87%|████████▋ | 137/157 [01:03<00:05,  3.97it/s]

PermutationExplainer explainer:  88%|████████▊ | 138/157 [01:04<00:04,  3.86it/s]

PermutationExplainer explainer:  89%|████████▊ | 139/157 [01:04<00:04,  3.94it/s]

PermutationExplainer explainer:  89%|████████▉ | 140/157 [01:04<00:04,  4.03it/s]

PermutationExplainer explainer:  90%|████████▉ | 141/157 [01:04<00:03,  4.06it/s]

PermutationExplainer explainer:  90%|█████████ | 142/157 [01:05<00:03,  3.92it/s]

PermutationExplainer explainer:  91%|█████████ | 143/157 [01:05<00:03,  3.84it/s]

PermutationExplainer explainer:  92%|█████████▏| 144/157 [01:05<00:03,  3.98it/s]

PermutationExplainer explainer:  92%|█████████▏| 145/157 [01:05<00:02,  4.12it/s]

PermutationExplainer explainer:  93%|█████████▎| 146/157 [01:06<00:02,  4.22it/s]

PermutationExplainer explainer:  94%|█████████▎| 147/157 [01:06<00:02,  4.10it/s]

PermutationExplainer explainer:  94%|█████████▍| 148/157 [01:06<00:02,  3.95it/s]

PermutationExplainer explainer:  95%|█████████▍| 149/157 [01:06<00:01,  4.03it/s]

PermutationExplainer explainer:  96%|█████████▌| 150/157 [01:07<00:01,  4.14it/s]

PermutationExplainer explainer:  96%|█████████▌| 151/157 [01:07<00:01,  4.19it/s]

PermutationExplainer explainer:  97%|█████████▋| 152/157 [01:07<00:01,  4.02it/s]

PermutationExplainer explainer:  97%|█████████▋| 153/157 [01:07<00:01,  3.83it/s]

PermutationExplainer explainer:  98%|█████████▊| 154/157 [01:08<00:00,  3.98it/s]

PermutationExplainer explainer:  99%|█████████▊| 155/157 [01:08<00:00,  4.07it/s]

PermutationExplainer explainer:  99%|█████████▉| 156/157 [01:08<00:00,  4.07it/s]

PermutationExplainer explainer: 100%|██████████| 157/157 [01:08<00:00,  3.97it/s]

PermutationExplainer explainer: 158it [01:09,  3.99it/s]

PermutationExplainer explainer: 158it [01:09,  2.27it/s]

C:\Users\Ponce\Documents\Maching_Learning_UES\prediccion_precios_agricolas\src\prediccion_precios\interpretability.py:77: FutureWarning: The NumPy global RNG was seeded by calling `np.random.seed`. In a future version this function will no longer use the global RNG. Pass `rng` explicitly to opt-in to the new behaviour and silence this warning.
  shap.summary_plot(shap_values, X_muestra, show=False)

WindowsPath('C:/Users/Ponce/Documents/Maching_Learning_UES/prediccion_precios_agricolas/reports/figures/shap_summary.png')

## 5. Guardar los modelos entrenados

In [7]:
for nombre, modelo in modelos.items():
    mb.guardar_modelo(modelo, nombre)
print("Modelos guardados en", config.MODELS_DIR)

Modelos guardados en C:\Users\Ponce\Documents\Maching_Learning_UES\prediccion_precios_agricolas\models

### Conclusiones de Etapa 1
> Indicar el mejor baseline, su MAPE frente a la meta (<15%), las variables más
> influyentes según SHAP y los próximos pasos hacia la Etapa 2 (optimización de
> hiperparámetros, LSTM/redes neuronales y ensemble).